# Generated by Django 5.0.4 on 2024-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fundacion', models.CharField(max_length=100)),
                ('nombre_responsable', models.CharField(max_length=100)),
                ('numero_celular', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('pagina_web', models.URLField(blank=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100)),
            ],
        ),
    ]
