# Generated by Django 5.0.4 on 2024-04-13 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundaciones', '0002_fundacion_gestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adolescente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=200)),
                ('edad', models.PositiveIntegerField()),
                ('canalizada_por', models.CharField(max_length=200)),
                ('escolaridad_actual', models.CharField(max_length=200)),
                ('tutor_responsable_nombre', models.CharField(max_length=200)),
                ('tutor_responsable_apellidos', models.CharField(max_length=200)),
                ('tutor_responsable_telefono', models.CharField(max_length=15)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('pertenece_etnia', models.BooleanField(default=False)),
                ('tiene_discapacidad', models.BooleanField(default=False)),
                ('discapacidad_detalle', models.CharField(blank=True, max_length=200)),
                ('diagnostico_psicologico', models.BooleanField(default=False)),
                ('diagnostico_detalle', models.CharField(blank=True, max_length=200)),
                ('tiene_hijos', models.BooleanField(default=False)),
                ('posee_acta_nacimiento', models.BooleanField(default=False)),
                ('posee_seguro_social', models.BooleanField(default=False)),
                ('posee_curp', models.BooleanField(default=False)),
                ('estudia_actualmente', models.BooleanField(default=False)),
                ('lugar_estudios', models.CharField(blank=True, max_length=200)),
                ('trabaja_actualmente', models.BooleanField(default=False)),
                ('lugar_trabajo', models.CharField(blank=True, max_length=200)),
                ('impedimento_continuar_estudios', models.TextField(blank=True)),
                ('fundacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adolescentes_inscritas', to='fundaciones.fundacion')),
            ],
        ),
    ]
