# Generated by Django 5.0.4 on 2024-04-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0001_initial'),
        ('cursos', '0002_alter_curso_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescente',
            name='cursos',
            field=models.ManyToManyField(related_name='adolescentes_inscritos', to='cursos.curso'),
        ),
    ]
