# Generated by Django 5.0.4 on 2024-04-24 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0002_cursosinscrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_modulo', models.BooleanField(default=False)),
                ('segundo_modulo', models.BooleanField(default=False)),
                ('tercer_modulo', models.BooleanField(default=False)),
                ('cuarto_modulo', models.BooleanField(default=False)),
                ('adolescente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Progreso_del_adolescente', to='Adolescentes.adolescente')),
            ],
        ),
    ]
