# Generated by Django 5.0.4 on 2024-04-21 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0003_remove_adolescente_cursos'),
        ('cursos', '0002_alter_curso_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosAdolescentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_created=True)),
                ('es_terminado', models.BooleanField()),
                ('adolescentes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Adolescentes.adolescente')),
                ('cursos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
        ),
    ]
