# Generated by Django 5.0.4 on 2024-04-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0004_cursosadolescentes'),
        ('cursos', '0002_alter_curso_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CursosAdolescentes',
            new_name='CursosInscrito',
        ),
    ]
