# Generated by Django 5.0.4 on 2024-04-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0005_rename_nacionalidad_otra_adolescente_otra_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescente',
            name='discapacidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adolescente',
            name='edad',
            field=models.PositiveSmallIntegerField(choices=[(13, 13), (14, 14), (15, 15), (16, 16), (17, 17)]),
        ),
        migrations.AlterField(
            model_name='adolescente',
            name='etnia',
            field=models.CharField(max_length=100),
        ),
    ]
