# Generated by Django 5.0.4 on 2024-04-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0006_alter_adolescente_discapacidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adolescente',
            name='etnia',
        ),
        migrations.AddField(
            model_name='adolescente',
            name='pertenece_etnia',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='adolescente',
            name='discapacidad',
            field=models.CharField(choices=[('NINGUNA', 'Ninguna'), ('FISICA/MOTRIZ', 'Discapacidad Física/Motriz'), ('SENSORIAL', 'Discapacidad Sensorial'), ('INTELECTUAL', 'Discapacidad Intelectual'), ('PSÍQUICA', 'Discapacidad Psíquica')], default='Ninguna', max_length=100),
        ),
    ]
