# Generated by Django 5.0.4 on 2024-04-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0007_remove_adolescente_etnia_adolescente_pertenece_etnia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosinscrito',
            name='es_terminado',
            field=models.BooleanField(choices=[(True, 'TERMINADO'), (False, 'PENDIENTE')], default=False),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='cuarto_modulo',
            field=models.BooleanField(choices=[(True, 'TERMINADO'), (False, 'PENDIENTE')], default=False),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='primer_modulo',
            field=models.BooleanField(choices=[(True, 'TERMINADO'), (False, 'PENDIENTE')], default=False),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='segundo_modulo',
            field=models.BooleanField(choices=[(True, 'TERMINADO'), (False, 'PENDIENTE')], default=False),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='tercer_modulo',
            field=models.BooleanField(choices=[(True, 'TERMINADO'), (False, 'PENDIENTE')], default=False),
        ),
    ]
