# Generated by Django 4.1.3 on 2024-04-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0008_alter_cursosinscrito_es_terminado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progreso',
            old_name='cuarto_modulo',
            new_name='Autoestima',
        ),
        migrations.RenameField(
            model_name='progreso',
            old_name='primer_modulo',
            new_name='Derechos_humanos',
        ),
        migrations.RenameField(
            model_name='progreso',
            old_name='segundo_modulo',
            new_name='Habilidades_sociales',
        ),
        migrations.RenameField(
            model_name='progreso',
            old_name='tercer_modulo',
            new_name='Necesidades_e_intereses',
        ),
    ]
