# Generated by Django 5.0.4 on 2024-05-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0009_rename_cuarto_modulo_progreso_autoestima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescente',
            name='escolaridad_actual',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachillerato', 'Bachillerato'), ('Licenciatura', 'Licenciatura')], default='Secundaria', max_length=200),
        ),
    ]
