# Generated by Django 5.0.4 on 2024-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0010_alter_adolescente_escolaridad_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosinscrito',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
    ]
