# Generated by Django 5.0.4 on 2024-05-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0011_cursosinscrito_es_destacado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adolescente',
            old_name='diagnostico_detalle',
            new_name='detalle_de_valoracion',
        ),
        migrations.RenameField(
            model_name='adolescente',
            old_name='diagnostico_psicologico',
            new_name='valoracion_psicologico',
        ),
    ]
