# Generated by Django 5.0.4 on 2024-05-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adolescentes', '0012_rename_diagnostico_detalle_adolescente_detalle_de_valoracion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adolescente',
            old_name='valoracion_psicologico',
            new_name='valoracion_psicologica',
        ),
    ]
